# Generated by Django 4.2.3 on 2023-08-05 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('question', models.CharField(max_length=200)),
                ('choices', models.JSONField()),
                ('correct_choice', models.IntegerField()),
            ],
        ),
    ]
