# Generated by Django 4.2.3 on 2023-09-10 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_generatedmcq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GeneratedMCQ',
        ),
    ]
